uint64 utime
string frame_id
Color color
float64 point_size
float64 line_width
bool on_off true
uint32 level 0
bool moves_to_map_plane false
string level_name

Points      points
Lines       lines
LineStrip   line_strip
Arrow       arrow
Triangles   triangles
Sphere      sphere
Cube        cube
Polygon     polygon
Text        text
TimeLine    timeline
GridMap     grid
LineStrips  line_strips
Arrows      arrows
Points2D    points2d
Lines2D     lines2d
LineStrip2D line_strip2d
LineStrips2D line_strips2d
Rectangles  rectangles
EllipseCurves  ellipse_curves

bool has_points
bool has_lines
bool has_line_strip
bool has_arrow
bool has_triangles
bool has_sphere
bool has_cube
bool has_polygon
bool has_text
bool has_timeline
bool has_grid
bool has_line_strips
bool has_arrows
bool has_points2d
bool has_lines2d
bool has_line_strip2d
bool has_line_strips2d
bool has_rectangles
bool has_ellipse_curves