uint8 local_lidar_consistency
uint8 gnss_consistency
uint8 local_lidar_status
uint8 local_lidar_quality
uint8 gnsspos_position_type
uint8 msf_running_status

# ImuMsgDelayStatus constant
uint8 IMU_DELAY_NORMAL = 0
uint8 IMU_DELAY_1 = 1
uint8 IMU_DELAY_2 = 2
uint8 IMU_DELAY_3 = 3
uint8 IMU_DELAY_ABNORMAL = 4
 
 
# ImuMsgMissingStatus constant
uint8 IMU_MISSING_NORMAL = 0
uint8 IMU_MISSING_1 = 1
uint8 IMU_MISSING_2 = 2
uint8 IMU_MISSING_3 = 3
uint8 IMU_MISSING_4 = 4
uint8 IMU_MISSING_5 = 5
uint8 IMU_MISSING_ABNORMAL = 6
 
 
# ImuMsgDataStatus constant
uint8 IMU_DATA_NORMAL = 0
uint8 IMU_DATA_ABNORMAL = 1
uint8 IMU_DATA_OTHER = 2
 