// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: image.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_image_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_image_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3014000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3014000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "header.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_image_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_image_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[3]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_image_2eproto;
namespace crdc {
namespace airi {
class CompressedImage;
class CompressedImageDefaultTypeInternal;
extern CompressedImageDefaultTypeInternal _CompressedImage_default_instance_;
class Image;
class ImageDefaultTypeInternal;
extern ImageDefaultTypeInternal _Image_default_instance_;
class Image2;
class Image2DefaultTypeInternal;
extern Image2DefaultTypeInternal _Image2_default_instance_;
}  // namespace airi
}  // namespace crdc
PROTOBUF_NAMESPACE_OPEN
template<> ::crdc::airi::CompressedImage* Arena::CreateMaybeMessage<::crdc::airi::CompressedImage>(Arena*);
template<> ::crdc::airi::Image* Arena::CreateMaybeMessage<::crdc::airi::Image>(Arena*);
template<> ::crdc::airi::Image2* Arena::CreateMaybeMessage<::crdc::airi::Image2>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace crdc {
namespace airi {

enum Image2_Compression : int {
  Image2_Compression_RAW = 1,
  Image2_Compression_JPEG = 2
};
bool Image2_Compression_IsValid(int value);
constexpr Image2_Compression Image2_Compression_Compression_MIN = Image2_Compression_RAW;
constexpr Image2_Compression Image2_Compression_Compression_MAX = Image2_Compression_JPEG;
constexpr int Image2_Compression_Compression_ARRAYSIZE = Image2_Compression_Compression_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Image2_Compression_descriptor();
template<typename T>
inline const std::string& Image2_Compression_Name(T enum_t_value) {
  static_assert(::std::is_same<T, Image2_Compression>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function Image2_Compression_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    Image2_Compression_descriptor(), enum_t_value);
}
inline bool Image2_Compression_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, Image2_Compression* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<Image2_Compression>(
    Image2_Compression_descriptor(), name, value);
}
enum PixelFormat : int {
  RGB8 = 1001,
  RGBA8 = 1002,
  RGB16 = 1003,
  RGBA16 = 1004,
  BGR8 = 1005,
  BGRA8 = 1006,
  BGR16 = 1007,
  BGRA16 = 1008,
  MONO8 = 1009,
  MONO16 = 1010,
  TYPE_8UC1 = 2001,
  TYPE_8UC2 = 2002,
  TYPE_8UC3 = 2003,
  TYPE_8UC4 = 2004,
  TYPE_8SC1 = 2005,
  TYPE_8SC2 = 2006,
  TYPE_8SC3 = 2007,
  TYPE_8SC4 = 2008,
  TYPE_16UC1 = 2009,
  TYPE_16UC2 = 2010,
  TYPE_16UC3 = 2011,
  TYPE_16UC4 = 2012,
  TYPE_16SC1 = 2013,
  TYPE_16SC2 = 2014,
  TYPE_16SC3 = 2015,
  TYPE_16SC4 = 2016,
  TYPE_32SC1 = 2017,
  TYPE_32SC2 = 2018,
  TYPE_32SC3 = 2019,
  TYPE_32SC4 = 2020,
  TYPE_32FC1 = 2021,
  TYPE_32FC2 = 2022,
  TYPE_32FC3 = 2023,
  TYPE_32FC4 = 2024,
  TYPE_64FC1 = 2025,
  TYPE_64FC2 = 2026,
  TYPE_64FC3 = 2027,
  TYPE_64FC4 = 2028,
  BAYER_RGGB8 = 3001,
  BAYER_BGGR8 = 3002,
  BAYER_GBRG8 = 3003,
  BAYER_GRBG8 = 3004,
  BAYER_RGGB16 = 3005,
  BAYER_BGGR16 = 3006,
  BAYER_GBRG16 = 3007,
  BAYER_GRBG16 = 3008,
  YUV422 = 4001,
  YUV420 = 4002,
  YUV444 = 4003,
  UYUV = 5001
};
bool PixelFormat_IsValid(int value);
constexpr PixelFormat PixelFormat_MIN = RGB8;
constexpr PixelFormat PixelFormat_MAX = UYUV;
constexpr int PixelFormat_ARRAYSIZE = PixelFormat_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* PixelFormat_descriptor();
template<typename T>
inline const std::string& PixelFormat_Name(T enum_t_value) {
  static_assert(::std::is_same<T, PixelFormat>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function PixelFormat_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    PixelFormat_descriptor(), enum_t_value);
}
inline bool PixelFormat_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, PixelFormat* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<PixelFormat>(
    PixelFormat_descriptor(), name, value);
}
// ===================================================================

class Image PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:crdc.airi.Image) */ {
 public:
  inline Image() : Image(nullptr) {}
  virtual ~Image();

  Image(const Image& from);
  Image(Image&& from) noexcept
    : Image() {
    *this = ::std::move(from);
  }

  inline Image& operator=(const Image& from) {
    CopyFrom(from);
    return *this;
  }
  inline Image& operator=(Image&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Image& default_instance();

  static inline const Image* internal_default_instance() {
    return reinterpret_cast<const Image*>(
               &_Image_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Image& a, Image& b) {
    a.Swap(&b);
  }
  inline void Swap(Image* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Image* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Image* New() const final {
    return CreateMaybeMessage<Image>(nullptr);
  }

  Image* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Image>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Image& from);
  void MergeFrom(const Image& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Image* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "crdc.airi.Image";
  }
  protected:
  explicit Image(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_image_2eproto);
    return ::descriptor_table_image_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFrameIdFieldNumber = 2,
    kEncodingFieldNumber = 6,
    kDataFieldNumber = 8,
    kHeaderFieldNumber = 1,
    kMeasurementTimeFieldNumber = 3,
    kHeightFieldNumber = 4,
    kWidthFieldNumber = 5,
    kStepFieldNumber = 7,
  };
  // optional string frame_id = 2;
  bool has_frame_id() const;
  private:
  bool _internal_has_frame_id() const;
  public:
  void clear_frame_id();
  const std::string& frame_id() const;
  void set_frame_id(const std::string& value);
  void set_frame_id(std::string&& value);
  void set_frame_id(const char* value);
  void set_frame_id(const char* value, size_t size);
  std::string* mutable_frame_id();
  std::string* release_frame_id();
  void set_allocated_frame_id(std::string* frame_id);
  private:
  const std::string& _internal_frame_id() const;
  void _internal_set_frame_id(const std::string& value);
  std::string* _internal_mutable_frame_id();
  public:

  // optional string encoding = 6;
  bool has_encoding() const;
  private:
  bool _internal_has_encoding() const;
  public:
  void clear_encoding();
  const std::string& encoding() const;
  void set_encoding(const std::string& value);
  void set_encoding(std::string&& value);
  void set_encoding(const char* value);
  void set_encoding(const char* value, size_t size);
  std::string* mutable_encoding();
  std::string* release_encoding();
  void set_allocated_encoding(std::string* encoding);
  private:
  const std::string& _internal_encoding() const;
  void _internal_set_encoding(const std::string& value);
  std::string* _internal_mutable_encoding();
  public:

  // optional bytes data = 8;
  bool has_data() const;
  private:
  bool _internal_has_data() const;
  public:
  void clear_data();
  const std::string& data() const;
  void set_data(const std::string& value);
  void set_data(std::string&& value);
  void set_data(const char* value);
  void set_data(const void* value, size_t size);
  std::string* mutable_data();
  std::string* release_data();
  void set_allocated_data(std::string* data);
  private:
  const std::string& _internal_data() const;
  void _internal_set_data(const std::string& value);
  std::string* _internal_mutable_data();
  public:

  // optional .crdc.airi.Header header = 1;
  bool has_header() const;
  private:
  bool _internal_has_header() const;
  public:
  void clear_header();
  const ::crdc::airi::Header& header() const;
  ::crdc::airi::Header* release_header();
  ::crdc::airi::Header* mutable_header();
  void set_allocated_header(::crdc::airi::Header* header);
  private:
  const ::crdc::airi::Header& _internal_header() const;
  ::crdc::airi::Header* _internal_mutable_header();
  public:
  void unsafe_arena_set_allocated_header(
      ::crdc::airi::Header* header);
  ::crdc::airi::Header* unsafe_arena_release_header();

  // optional double measurement_time = 3;
  bool has_measurement_time() const;
  private:
  bool _internal_has_measurement_time() const;
  public:
  void clear_measurement_time();
  double measurement_time() const;
  void set_measurement_time(double value);
  private:
  double _internal_measurement_time() const;
  void _internal_set_measurement_time(double value);
  public:

  // optional uint32 height = 4;
  bool has_height() const;
  private:
  bool _internal_has_height() const;
  public:
  void clear_height();
  ::PROTOBUF_NAMESPACE_ID::uint32 height() const;
  void set_height(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_height() const;
  void _internal_set_height(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // optional uint32 width = 5;
  bool has_width() const;
  private:
  bool _internal_has_width() const;
  public:
  void clear_width();
  ::PROTOBUF_NAMESPACE_ID::uint32 width() const;
  void set_width(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_width() const;
  void _internal_set_width(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // optional uint32 step = 7;
  bool has_step() const;
  private:
  bool _internal_has_step() const;
  public:
  void clear_step();
  ::PROTOBUF_NAMESPACE_ID::uint32 step() const;
  void set_step(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_step() const;
  void _internal_set_step(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:crdc.airi.Image)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr frame_id_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr encoding_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr data_;
  ::crdc::airi::Header* header_;
  double measurement_time_;
  ::PROTOBUF_NAMESPACE_ID::uint32 height_;
  ::PROTOBUF_NAMESPACE_ID::uint32 width_;
  ::PROTOBUF_NAMESPACE_ID::uint32 step_;
  friend struct ::TableStruct_image_2eproto;
};
// -------------------------------------------------------------------

class CompressedImage PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:crdc.airi.CompressedImage) */ {
 public:
  inline CompressedImage() : CompressedImage(nullptr) {}
  virtual ~CompressedImage();

  CompressedImage(const CompressedImage& from);
  CompressedImage(CompressedImage&& from) noexcept
    : CompressedImage() {
    *this = ::std::move(from);
  }

  inline CompressedImage& operator=(const CompressedImage& from) {
    CopyFrom(from);
    return *this;
  }
  inline CompressedImage& operator=(CompressedImage&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const CompressedImage& default_instance();

  static inline const CompressedImage* internal_default_instance() {
    return reinterpret_cast<const CompressedImage*>(
               &_CompressedImage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(CompressedImage& a, CompressedImage& b) {
    a.Swap(&b);
  }
  inline void Swap(CompressedImage* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CompressedImage* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline CompressedImage* New() const final {
    return CreateMaybeMessage<CompressedImage>(nullptr);
  }

  CompressedImage* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<CompressedImage>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const CompressedImage& from);
  void MergeFrom(const CompressedImage& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CompressedImage* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "crdc.airi.CompressedImage";
  }
  protected:
  explicit CompressedImage(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_image_2eproto);
    return ::descriptor_table_image_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFrameIdFieldNumber = 2,
    kFormatFieldNumber = 3,
    kDataFieldNumber = 4,
    kHeaderFieldNumber = 1,
    kMeasurementTimeFieldNumber = 5,
    kFrameTypeFieldNumber = 6,
  };
  // optional string frame_id = 2;
  bool has_frame_id() const;
  private:
  bool _internal_has_frame_id() const;
  public:
  void clear_frame_id();
  const std::string& frame_id() const;
  void set_frame_id(const std::string& value);
  void set_frame_id(std::string&& value);
  void set_frame_id(const char* value);
  void set_frame_id(const char* value, size_t size);
  std::string* mutable_frame_id();
  std::string* release_frame_id();
  void set_allocated_frame_id(std::string* frame_id);
  private:
  const std::string& _internal_frame_id() const;
  void _internal_set_frame_id(const std::string& value);
  std::string* _internal_mutable_frame_id();
  public:

  // optional string format = 3;
  bool has_format() const;
  private:
  bool _internal_has_format() const;
  public:
  void clear_format();
  const std::string& format() const;
  void set_format(const std::string& value);
  void set_format(std::string&& value);
  void set_format(const char* value);
  void set_format(const char* value, size_t size);
  std::string* mutable_format();
  std::string* release_format();
  void set_allocated_format(std::string* format);
  private:
  const std::string& _internal_format() const;
  void _internal_set_format(const std::string& value);
  std::string* _internal_mutable_format();
  public:

  // optional bytes data = 4;
  bool has_data() const;
  private:
  bool _internal_has_data() const;
  public:
  void clear_data();
  const std::string& data() const;
  void set_data(const std::string& value);
  void set_data(std::string&& value);
  void set_data(const char* value);
  void set_data(const void* value, size_t size);
  std::string* mutable_data();
  std::string* release_data();
  void set_allocated_data(std::string* data);
  private:
  const std::string& _internal_data() const;
  void _internal_set_data(const std::string& value);
  std::string* _internal_mutable_data();
  public:

  // optional .crdc.airi.Header header = 1;
  bool has_header() const;
  private:
  bool _internal_has_header() const;
  public:
  void clear_header();
  const ::crdc::airi::Header& header() const;
  ::crdc::airi::Header* release_header();
  ::crdc::airi::Header* mutable_header();
  void set_allocated_header(::crdc::airi::Header* header);
  private:
  const ::crdc::airi::Header& _internal_header() const;
  ::crdc::airi::Header* _internal_mutable_header();
  public:
  void unsafe_arena_set_allocated_header(
      ::crdc::airi::Header* header);
  ::crdc::airi::Header* unsafe_arena_release_header();

  // optional double measurement_time = 5;
  bool has_measurement_time() const;
  private:
  bool _internal_has_measurement_time() const;
  public:
  void clear_measurement_time();
  double measurement_time() const;
  void set_measurement_time(double value);
  private:
  double _internal_measurement_time() const;
  void _internal_set_measurement_time(double value);
  public:

  // optional uint32 frame_type = 6;
  bool has_frame_type() const;
  private:
  bool _internal_has_frame_type() const;
  public:
  void clear_frame_type();
  ::PROTOBUF_NAMESPACE_ID::uint32 frame_type() const;
  void set_frame_type(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_frame_type() const;
  void _internal_set_frame_type(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:crdc.airi.CompressedImage)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr frame_id_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr format_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr data_;
  ::crdc::airi::Header* header_;
  double measurement_time_;
  ::PROTOBUF_NAMESPACE_ID::uint32 frame_type_;
  friend struct ::TableStruct_image_2eproto;
};
// -------------------------------------------------------------------

class Image2 PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:crdc.airi.Image2) */ {
 public:
  inline Image2() : Image2(nullptr) {}
  virtual ~Image2();

  Image2(const Image2& from);
  Image2(Image2&& from) noexcept
    : Image2() {
    *this = ::std::move(from);
  }

  inline Image2& operator=(const Image2& from) {
    CopyFrom(from);
    return *this;
  }
  inline Image2& operator=(Image2&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Image2& default_instance();

  static inline const Image2* internal_default_instance() {
    return reinterpret_cast<const Image2*>(
               &_Image2_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(Image2& a, Image2& b) {
    a.Swap(&b);
  }
  inline void Swap(Image2* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Image2* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Image2* New() const final {
    return CreateMaybeMessage<Image2>(nullptr);
  }

  Image2* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Image2>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Image2& from);
  void MergeFrom(const Image2& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Image2* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "crdc.airi.Image2";
  }
  protected:
  explicit Image2(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_image_2eproto);
    return ::descriptor_table_image_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  typedef Image2_Compression Compression;
  static constexpr Compression RAW =
    Image2_Compression_RAW;
  static constexpr Compression JPEG =
    Image2_Compression_JPEG;
  static inline bool Compression_IsValid(int value) {
    return Image2_Compression_IsValid(value);
  }
  static constexpr Compression Compression_MIN =
    Image2_Compression_Compression_MIN;
  static constexpr Compression Compression_MAX =
    Image2_Compression_Compression_MAX;
  static constexpr int Compression_ARRAYSIZE =
    Image2_Compression_Compression_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  Compression_descriptor() {
    return Image2_Compression_descriptor();
  }
  template<typename T>
  static inline const std::string& Compression_Name(T enum_t_value) {
    static_assert(::std::is_same<T, Compression>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function Compression_Name.");
    return Image2_Compression_Name(enum_t_value);
  }
  static inline bool Compression_Parse(::PROTOBUF_NAMESPACE_ID::ConstStringParam name,
      Compression* value) {
    return Image2_Compression_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kDataFieldNumber = 6,
    kTypeFieldNumber = 7,
    kHeaderFieldNumber = 1,
    kHeightFieldNumber = 2,
    kWidthFieldNumber = 3,
    kStepFieldNumber = 5,
    kExposuretimeFieldNumber = 8,
    kCompressionFieldNumber = 4,
  };
  // optional bytes data = 6;
  bool has_data() const;
  private:
  bool _internal_has_data() const;
  public:
  void clear_data();
  const std::string& data() const;
  void set_data(const std::string& value);
  void set_data(std::string&& value);
  void set_data(const char* value);
  void set_data(const void* value, size_t size);
  std::string* mutable_data();
  std::string* release_data();
  void set_allocated_data(std::string* data);
  private:
  const std::string& _internal_data() const;
  void _internal_set_data(const std::string& value);
  std::string* _internal_mutable_data();
  public:

  // optional string type = 7;
  bool has_type() const;
  private:
  bool _internal_has_type() const;
  public:
  void clear_type();
  const std::string& type() const;
  void set_type(const std::string& value);
  void set_type(std::string&& value);
  void set_type(const char* value);
  void set_type(const char* value, size_t size);
  std::string* mutable_type();
  std::string* release_type();
  void set_allocated_type(std::string* type);
  private:
  const std::string& _internal_type() const;
  void _internal_set_type(const std::string& value);
  std::string* _internal_mutable_type();
  public:

  // optional .crdc.airi.Header header = 1;
  bool has_header() const;
  private:
  bool _internal_has_header() const;
  public:
  void clear_header();
  const ::crdc::airi::Header& header() const;
  ::crdc::airi::Header* release_header();
  ::crdc::airi::Header* mutable_header();
  void set_allocated_header(::crdc::airi::Header* header);
  private:
  const ::crdc::airi::Header& _internal_header() const;
  ::crdc::airi::Header* _internal_mutable_header();
  public:
  void unsafe_arena_set_allocated_header(
      ::crdc::airi::Header* header);
  ::crdc::airi::Header* unsafe_arena_release_header();

  // optional uint32 height = 2;
  bool has_height() const;
  private:
  bool _internal_has_height() const;
  public:
  void clear_height();
  ::PROTOBUF_NAMESPACE_ID::uint32 height() const;
  void set_height(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_height() const;
  void _internal_set_height(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // optional uint32 width = 3;
  bool has_width() const;
  private:
  bool _internal_has_width() const;
  public:
  void clear_width();
  ::PROTOBUF_NAMESPACE_ID::uint32 width() const;
  void set_width(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_width() const;
  void _internal_set_width(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // optional uint32 step = 5;
  bool has_step() const;
  private:
  bool _internal_has_step() const;
  public:
  void clear_step();
  ::PROTOBUF_NAMESPACE_ID::uint32 step() const;
  void set_step(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_step() const;
  void _internal_set_step(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // optional uint32 exposuretime = 8;
  bool has_exposuretime() const;
  private:
  bool _internal_has_exposuretime() const;
  public:
  void clear_exposuretime();
  ::PROTOBUF_NAMESPACE_ID::uint32 exposuretime() const;
  void set_exposuretime(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_exposuretime() const;
  void _internal_set_exposuretime(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // optional .crdc.airi.Image2.Compression compression = 4;
  bool has_compression() const;
  private:
  bool _internal_has_compression() const;
  public:
  void clear_compression();
  ::crdc::airi::Image2_Compression compression() const;
  void set_compression(::crdc::airi::Image2_Compression value);
  private:
  ::crdc::airi::Image2_Compression _internal_compression() const;
  void _internal_set_compression(::crdc::airi::Image2_Compression value);
  public:

  // @@protoc_insertion_point(class_scope:crdc.airi.Image2)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr data_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr type_;
  ::crdc::airi::Header* header_;
  ::PROTOBUF_NAMESPACE_ID::uint32 height_;
  ::PROTOBUF_NAMESPACE_ID::uint32 width_;
  ::PROTOBUF_NAMESPACE_ID::uint32 step_;
  ::PROTOBUF_NAMESPACE_ID::uint32 exposuretime_;
  int compression_;
  friend struct ::TableStruct_image_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Image

// optional .crdc.airi.Header header = 1;
inline bool Image::_internal_has_header() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  PROTOBUF_ASSUME(!value || header_ != nullptr);
  return value;
}
inline bool Image::has_header() const {
  return _internal_has_header();
}
inline const ::crdc::airi::Header& Image::_internal_header() const {
  const ::crdc::airi::Header* p = header_;
  return p != nullptr ? *p : reinterpret_cast<const ::crdc::airi::Header&>(
      ::crdc::airi::_Header_default_instance_);
}
inline const ::crdc::airi::Header& Image::header() const {
  // @@protoc_insertion_point(field_get:crdc.airi.Image.header)
  return _internal_header();
}
inline void Image::unsafe_arena_set_allocated_header(
    ::crdc::airi::Header* header) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(header_);
  }
  header_ = header;
  if (header) {
    _has_bits_[0] |= 0x00000008u;
  } else {
    _has_bits_[0] &= ~0x00000008u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:crdc.airi.Image.header)
}
inline ::crdc::airi::Header* Image::release_header() {
  _has_bits_[0] &= ~0x00000008u;
  ::crdc::airi::Header* temp = header_;
  header_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::crdc::airi::Header* Image::unsafe_arena_release_header() {
  // @@protoc_insertion_point(field_release:crdc.airi.Image.header)
  _has_bits_[0] &= ~0x00000008u;
  ::crdc::airi::Header* temp = header_;
  header_ = nullptr;
  return temp;
}
inline ::crdc::airi::Header* Image::_internal_mutable_header() {
  _has_bits_[0] |= 0x00000008u;
  if (header_ == nullptr) {
    auto* p = CreateMaybeMessage<::crdc::airi::Header>(GetArena());
    header_ = p;
  }
  return header_;
}
inline ::crdc::airi::Header* Image::mutable_header() {
  // @@protoc_insertion_point(field_mutable:crdc.airi.Image.header)
  return _internal_mutable_header();
}
inline void Image::set_allocated_header(::crdc::airi::Header* header) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(header_);
  }
  if (header) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(header)->GetArena();
    if (message_arena != submessage_arena) {
      header = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, header, submessage_arena);
    }
    _has_bits_[0] |= 0x00000008u;
  } else {
    _has_bits_[0] &= ~0x00000008u;
  }
  header_ = header;
  // @@protoc_insertion_point(field_set_allocated:crdc.airi.Image.header)
}

// optional string frame_id = 2;
inline bool Image::_internal_has_frame_id() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool Image::has_frame_id() const {
  return _internal_has_frame_id();
}
inline void Image::clear_frame_id() {
  frame_id_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& Image::frame_id() const {
  // @@protoc_insertion_point(field_get:crdc.airi.Image.frame_id)
  return _internal_frame_id();
}
inline void Image::set_frame_id(const std::string& value) {
  _internal_set_frame_id(value);
  // @@protoc_insertion_point(field_set:crdc.airi.Image.frame_id)
}
inline std::string* Image::mutable_frame_id() {
  // @@protoc_insertion_point(field_mutable:crdc.airi.Image.frame_id)
  return _internal_mutable_frame_id();
}
inline const std::string& Image::_internal_frame_id() const {
  return frame_id_.Get();
}
inline void Image::_internal_set_frame_id(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  frame_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void Image::set_frame_id(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  frame_id_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:crdc.airi.Image.frame_id)
}
inline void Image::set_frame_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  frame_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:crdc.airi.Image.frame_id)
}
inline void Image::set_frame_id(const char* value,
    size_t size) {
  _has_bits_[0] |= 0x00000001u;
  frame_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:crdc.airi.Image.frame_id)
}
inline std::string* Image::_internal_mutable_frame_id() {
  _has_bits_[0] |= 0x00000001u;
  return frame_id_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* Image::release_frame_id() {
  // @@protoc_insertion_point(field_release:crdc.airi.Image.frame_id)
  if (!_internal_has_frame_id()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return frame_id_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void Image::set_allocated_frame_id(std::string* frame_id) {
  if (frame_id != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  frame_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), frame_id,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:crdc.airi.Image.frame_id)
}

// optional double measurement_time = 3;
inline bool Image::_internal_has_measurement_time() const {
  bool value = (_has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline bool Image::has_measurement_time() const {
  return _internal_has_measurement_time();
}
inline void Image::clear_measurement_time() {
  measurement_time_ = 0;
  _has_bits_[0] &= ~0x00000010u;
}
inline double Image::_internal_measurement_time() const {
  return measurement_time_;
}
inline double Image::measurement_time() const {
  // @@protoc_insertion_point(field_get:crdc.airi.Image.measurement_time)
  return _internal_measurement_time();
}
inline void Image::_internal_set_measurement_time(double value) {
  _has_bits_[0] |= 0x00000010u;
  measurement_time_ = value;
}
inline void Image::set_measurement_time(double value) {
  _internal_set_measurement_time(value);
  // @@protoc_insertion_point(field_set:crdc.airi.Image.measurement_time)
}

// optional uint32 height = 4;
inline bool Image::_internal_has_height() const {
  bool value = (_has_bits_[0] & 0x00000020u) != 0;
  return value;
}
inline bool Image::has_height() const {
  return _internal_has_height();
}
inline void Image::clear_height() {
  height_ = 0u;
  _has_bits_[0] &= ~0x00000020u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Image::_internal_height() const {
  return height_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Image::height() const {
  // @@protoc_insertion_point(field_get:crdc.airi.Image.height)
  return _internal_height();
}
inline void Image::_internal_set_height(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _has_bits_[0] |= 0x00000020u;
  height_ = value;
}
inline void Image::set_height(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_height(value);
  // @@protoc_insertion_point(field_set:crdc.airi.Image.height)
}

// optional uint32 width = 5;
inline bool Image::_internal_has_width() const {
  bool value = (_has_bits_[0] & 0x00000040u) != 0;
  return value;
}
inline bool Image::has_width() const {
  return _internal_has_width();
}
inline void Image::clear_width() {
  width_ = 0u;
  _has_bits_[0] &= ~0x00000040u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Image::_internal_width() const {
  return width_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Image::width() const {
  // @@protoc_insertion_point(field_get:crdc.airi.Image.width)
  return _internal_width();
}
inline void Image::_internal_set_width(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _has_bits_[0] |= 0x00000040u;
  width_ = value;
}
inline void Image::set_width(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_width(value);
  // @@protoc_insertion_point(field_set:crdc.airi.Image.width)
}

// optional string encoding = 6;
inline bool Image::_internal_has_encoding() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool Image::has_encoding() const {
  return _internal_has_encoding();
}
inline void Image::clear_encoding() {
  encoding_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000002u;
}
inline const std::string& Image::encoding() const {
  // @@protoc_insertion_point(field_get:crdc.airi.Image.encoding)
  return _internal_encoding();
}
inline void Image::set_encoding(const std::string& value) {
  _internal_set_encoding(value);
  // @@protoc_insertion_point(field_set:crdc.airi.Image.encoding)
}
inline std::string* Image::mutable_encoding() {
  // @@protoc_insertion_point(field_mutable:crdc.airi.Image.encoding)
  return _internal_mutable_encoding();
}
inline const std::string& Image::_internal_encoding() const {
  return encoding_.Get();
}
inline void Image::_internal_set_encoding(const std::string& value) {
  _has_bits_[0] |= 0x00000002u;
  encoding_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void Image::set_encoding(std::string&& value) {
  _has_bits_[0] |= 0x00000002u;
  encoding_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:crdc.airi.Image.encoding)
}
inline void Image::set_encoding(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000002u;
  encoding_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:crdc.airi.Image.encoding)
}
inline void Image::set_encoding(const char* value,
    size_t size) {
  _has_bits_[0] |= 0x00000002u;
  encoding_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:crdc.airi.Image.encoding)
}
inline std::string* Image::_internal_mutable_encoding() {
  _has_bits_[0] |= 0x00000002u;
  return encoding_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* Image::release_encoding() {
  // @@protoc_insertion_point(field_release:crdc.airi.Image.encoding)
  if (!_internal_has_encoding()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000002u;
  return encoding_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void Image::set_allocated_encoding(std::string* encoding) {
  if (encoding != nullptr) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  encoding_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), encoding,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:crdc.airi.Image.encoding)
}

// optional uint32 step = 7;
inline bool Image::_internal_has_step() const {
  bool value = (_has_bits_[0] & 0x00000080u) != 0;
  return value;
}
inline bool Image::has_step() const {
  return _internal_has_step();
}
inline void Image::clear_step() {
  step_ = 0u;
  _has_bits_[0] &= ~0x00000080u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Image::_internal_step() const {
  return step_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Image::step() const {
  // @@protoc_insertion_point(field_get:crdc.airi.Image.step)
  return _internal_step();
}
inline void Image::_internal_set_step(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _has_bits_[0] |= 0x00000080u;
  step_ = value;
}
inline void Image::set_step(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_step(value);
  // @@protoc_insertion_point(field_set:crdc.airi.Image.step)
}

// optional bytes data = 8;
inline bool Image::_internal_has_data() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool Image::has_data() const {
  return _internal_has_data();
}
inline void Image::clear_data() {
  data_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000004u;
}
inline const std::string& Image::data() const {
  // @@protoc_insertion_point(field_get:crdc.airi.Image.data)
  return _internal_data();
}
inline void Image::set_data(const std::string& value) {
  _internal_set_data(value);
  // @@protoc_insertion_point(field_set:crdc.airi.Image.data)
}
inline std::string* Image::mutable_data() {
  // @@protoc_insertion_point(field_mutable:crdc.airi.Image.data)
  return _internal_mutable_data();
}
inline const std::string& Image::_internal_data() const {
  return data_.Get();
}
inline void Image::_internal_set_data(const std::string& value) {
  _has_bits_[0] |= 0x00000004u;
  data_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void Image::set_data(std::string&& value) {
  _has_bits_[0] |= 0x00000004u;
  data_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:crdc.airi.Image.data)
}
inline void Image::set_data(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000004u;
  data_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:crdc.airi.Image.data)
}
inline void Image::set_data(const void* value,
    size_t size) {
  _has_bits_[0] |= 0x00000004u;
  data_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:crdc.airi.Image.data)
}
inline std::string* Image::_internal_mutable_data() {
  _has_bits_[0] |= 0x00000004u;
  return data_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* Image::release_data() {
  // @@protoc_insertion_point(field_release:crdc.airi.Image.data)
  if (!_internal_has_data()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000004u;
  return data_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void Image::set_allocated_data(std::string* data) {
  if (data != nullptr) {
    _has_bits_[0] |= 0x00000004u;
  } else {
    _has_bits_[0] &= ~0x00000004u;
  }
  data_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), data,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:crdc.airi.Image.data)
}

// -------------------------------------------------------------------

// CompressedImage

// optional .crdc.airi.Header header = 1;
inline bool CompressedImage::_internal_has_header() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  PROTOBUF_ASSUME(!value || header_ != nullptr);
  return value;
}
inline bool CompressedImage::has_header() const {
  return _internal_has_header();
}
inline const ::crdc::airi::Header& CompressedImage::_internal_header() const {
  const ::crdc::airi::Header* p = header_;
  return p != nullptr ? *p : reinterpret_cast<const ::crdc::airi::Header&>(
      ::crdc::airi::_Header_default_instance_);
}
inline const ::crdc::airi::Header& CompressedImage::header() const {
  // @@protoc_insertion_point(field_get:crdc.airi.CompressedImage.header)
  return _internal_header();
}
inline void CompressedImage::unsafe_arena_set_allocated_header(
    ::crdc::airi::Header* header) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(header_);
  }
  header_ = header;
  if (header) {
    _has_bits_[0] |= 0x00000008u;
  } else {
    _has_bits_[0] &= ~0x00000008u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:crdc.airi.CompressedImage.header)
}
inline ::crdc::airi::Header* CompressedImage::release_header() {
  _has_bits_[0] &= ~0x00000008u;
  ::crdc::airi::Header* temp = header_;
  header_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::crdc::airi::Header* CompressedImage::unsafe_arena_release_header() {
  // @@protoc_insertion_point(field_release:crdc.airi.CompressedImage.header)
  _has_bits_[0] &= ~0x00000008u;
  ::crdc::airi::Header* temp = header_;
  header_ = nullptr;
  return temp;
}
inline ::crdc::airi::Header* CompressedImage::_internal_mutable_header() {
  _has_bits_[0] |= 0x00000008u;
  if (header_ == nullptr) {
    auto* p = CreateMaybeMessage<::crdc::airi::Header>(GetArena());
    header_ = p;
  }
  return header_;
}
inline ::crdc::airi::Header* CompressedImage::mutable_header() {
  // @@protoc_insertion_point(field_mutable:crdc.airi.CompressedImage.header)
  return _internal_mutable_header();
}
inline void CompressedImage::set_allocated_header(::crdc::airi::Header* header) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(header_);
  }
  if (header) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(header)->GetArena();
    if (message_arena != submessage_arena) {
      header = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, header, submessage_arena);
    }
    _has_bits_[0] |= 0x00000008u;
  } else {
    _has_bits_[0] &= ~0x00000008u;
  }
  header_ = header;
  // @@protoc_insertion_point(field_set_allocated:crdc.airi.CompressedImage.header)
}

// optional string frame_id = 2;
inline bool CompressedImage::_internal_has_frame_id() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool CompressedImage::has_frame_id() const {
  return _internal_has_frame_id();
}
inline void CompressedImage::clear_frame_id() {
  frame_id_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& CompressedImage::frame_id() const {
  // @@protoc_insertion_point(field_get:crdc.airi.CompressedImage.frame_id)
  return _internal_frame_id();
}
inline void CompressedImage::set_frame_id(const std::string& value) {
  _internal_set_frame_id(value);
  // @@protoc_insertion_point(field_set:crdc.airi.CompressedImage.frame_id)
}
inline std::string* CompressedImage::mutable_frame_id() {
  // @@protoc_insertion_point(field_mutable:crdc.airi.CompressedImage.frame_id)
  return _internal_mutable_frame_id();
}
inline const std::string& CompressedImage::_internal_frame_id() const {
  return frame_id_.Get();
}
inline void CompressedImage::_internal_set_frame_id(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  frame_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void CompressedImage::set_frame_id(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  frame_id_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:crdc.airi.CompressedImage.frame_id)
}
inline void CompressedImage::set_frame_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  frame_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:crdc.airi.CompressedImage.frame_id)
}
inline void CompressedImage::set_frame_id(const char* value,
    size_t size) {
  _has_bits_[0] |= 0x00000001u;
  frame_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:crdc.airi.CompressedImage.frame_id)
}
inline std::string* CompressedImage::_internal_mutable_frame_id() {
  _has_bits_[0] |= 0x00000001u;
  return frame_id_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* CompressedImage::release_frame_id() {
  // @@protoc_insertion_point(field_release:crdc.airi.CompressedImage.frame_id)
  if (!_internal_has_frame_id()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return frame_id_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void CompressedImage::set_allocated_frame_id(std::string* frame_id) {
  if (frame_id != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  frame_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), frame_id,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:crdc.airi.CompressedImage.frame_id)
}

// optional string format = 3;
inline bool CompressedImage::_internal_has_format() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool CompressedImage::has_format() const {
  return _internal_has_format();
}
inline void CompressedImage::clear_format() {
  format_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000002u;
}
inline const std::string& CompressedImage::format() const {
  // @@protoc_insertion_point(field_get:crdc.airi.CompressedImage.format)
  return _internal_format();
}
inline void CompressedImage::set_format(const std::string& value) {
  _internal_set_format(value);
  // @@protoc_insertion_point(field_set:crdc.airi.CompressedImage.format)
}
inline std::string* CompressedImage::mutable_format() {
  // @@protoc_insertion_point(field_mutable:crdc.airi.CompressedImage.format)
  return _internal_mutable_format();
}
inline const std::string& CompressedImage::_internal_format() const {
  return format_.Get();
}
inline void CompressedImage::_internal_set_format(const std::string& value) {
  _has_bits_[0] |= 0x00000002u;
  format_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void CompressedImage::set_format(std::string&& value) {
  _has_bits_[0] |= 0x00000002u;
  format_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:crdc.airi.CompressedImage.format)
}
inline void CompressedImage::set_format(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000002u;
  format_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:crdc.airi.CompressedImage.format)
}
inline void CompressedImage::set_format(const char* value,
    size_t size) {
  _has_bits_[0] |= 0x00000002u;
  format_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:crdc.airi.CompressedImage.format)
}
inline std::string* CompressedImage::_internal_mutable_format() {
  _has_bits_[0] |= 0x00000002u;
  return format_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* CompressedImage::release_format() {
  // @@protoc_insertion_point(field_release:crdc.airi.CompressedImage.format)
  if (!_internal_has_format()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000002u;
  return format_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void CompressedImage::set_allocated_format(std::string* format) {
  if (format != nullptr) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  format_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), format,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:crdc.airi.CompressedImage.format)
}

// optional bytes data = 4;
inline bool CompressedImage::_internal_has_data() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool CompressedImage::has_data() const {
  return _internal_has_data();
}
inline void CompressedImage::clear_data() {
  data_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000004u;
}
inline const std::string& CompressedImage::data() const {
  // @@protoc_insertion_point(field_get:crdc.airi.CompressedImage.data)
  return _internal_data();
}
inline void CompressedImage::set_data(const std::string& value) {
  _internal_set_data(value);
  // @@protoc_insertion_point(field_set:crdc.airi.CompressedImage.data)
}
inline std::string* CompressedImage::mutable_data() {
  // @@protoc_insertion_point(field_mutable:crdc.airi.CompressedImage.data)
  return _internal_mutable_data();
}
inline const std::string& CompressedImage::_internal_data() const {
  return data_.Get();
}
inline void CompressedImage::_internal_set_data(const std::string& value) {
  _has_bits_[0] |= 0x00000004u;
  data_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void CompressedImage::set_data(std::string&& value) {
  _has_bits_[0] |= 0x00000004u;
  data_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:crdc.airi.CompressedImage.data)
}
inline void CompressedImage::set_data(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000004u;
  data_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:crdc.airi.CompressedImage.data)
}
inline void CompressedImage::set_data(const void* value,
    size_t size) {
  _has_bits_[0] |= 0x00000004u;
  data_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:crdc.airi.CompressedImage.data)
}
inline std::string* CompressedImage::_internal_mutable_data() {
  _has_bits_[0] |= 0x00000004u;
  return data_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* CompressedImage::release_data() {
  // @@protoc_insertion_point(field_release:crdc.airi.CompressedImage.data)
  if (!_internal_has_data()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000004u;
  return data_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void CompressedImage::set_allocated_data(std::string* data) {
  if (data != nullptr) {
    _has_bits_[0] |= 0x00000004u;
  } else {
    _has_bits_[0] &= ~0x00000004u;
  }
  data_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), data,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:crdc.airi.CompressedImage.data)
}

// optional double measurement_time = 5;
inline bool CompressedImage::_internal_has_measurement_time() const {
  bool value = (_has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline bool CompressedImage::has_measurement_time() const {
  return _internal_has_measurement_time();
}
inline void CompressedImage::clear_measurement_time() {
  measurement_time_ = 0;
  _has_bits_[0] &= ~0x00000010u;
}
inline double CompressedImage::_internal_measurement_time() const {
  return measurement_time_;
}
inline double CompressedImage::measurement_time() const {
  // @@protoc_insertion_point(field_get:crdc.airi.CompressedImage.measurement_time)
  return _internal_measurement_time();
}
inline void CompressedImage::_internal_set_measurement_time(double value) {
  _has_bits_[0] |= 0x00000010u;
  measurement_time_ = value;
}
inline void CompressedImage::set_measurement_time(double value) {
  _internal_set_measurement_time(value);
  // @@protoc_insertion_point(field_set:crdc.airi.CompressedImage.measurement_time)
}

// optional uint32 frame_type = 6;
inline bool CompressedImage::_internal_has_frame_type() const {
  bool value = (_has_bits_[0] & 0x00000020u) != 0;
  return value;
}
inline bool CompressedImage::has_frame_type() const {
  return _internal_has_frame_type();
}
inline void CompressedImage::clear_frame_type() {
  frame_type_ = 0u;
  _has_bits_[0] &= ~0x00000020u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 CompressedImage::_internal_frame_type() const {
  return frame_type_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 CompressedImage::frame_type() const {
  // @@protoc_insertion_point(field_get:crdc.airi.CompressedImage.frame_type)
  return _internal_frame_type();
}
inline void CompressedImage::_internal_set_frame_type(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _has_bits_[0] |= 0x00000020u;
  frame_type_ = value;
}
inline void CompressedImage::set_frame_type(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_frame_type(value);
  // @@protoc_insertion_point(field_set:crdc.airi.CompressedImage.frame_type)
}

// -------------------------------------------------------------------

// Image2

// optional .crdc.airi.Header header = 1;
inline bool Image2::_internal_has_header() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  PROTOBUF_ASSUME(!value || header_ != nullptr);
  return value;
}
inline bool Image2::has_header() const {
  return _internal_has_header();
}
inline const ::crdc::airi::Header& Image2::_internal_header() const {
  const ::crdc::airi::Header* p = header_;
  return p != nullptr ? *p : reinterpret_cast<const ::crdc::airi::Header&>(
      ::crdc::airi::_Header_default_instance_);
}
inline const ::crdc::airi::Header& Image2::header() const {
  // @@protoc_insertion_point(field_get:crdc.airi.Image2.header)
  return _internal_header();
}
inline void Image2::unsafe_arena_set_allocated_header(
    ::crdc::airi::Header* header) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(header_);
  }
  header_ = header;
  if (header) {
    _has_bits_[0] |= 0x00000004u;
  } else {
    _has_bits_[0] &= ~0x00000004u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:crdc.airi.Image2.header)
}
inline ::crdc::airi::Header* Image2::release_header() {
  _has_bits_[0] &= ~0x00000004u;
  ::crdc::airi::Header* temp = header_;
  header_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::crdc::airi::Header* Image2::unsafe_arena_release_header() {
  // @@protoc_insertion_point(field_release:crdc.airi.Image2.header)
  _has_bits_[0] &= ~0x00000004u;
  ::crdc::airi::Header* temp = header_;
  header_ = nullptr;
  return temp;
}
inline ::crdc::airi::Header* Image2::_internal_mutable_header() {
  _has_bits_[0] |= 0x00000004u;
  if (header_ == nullptr) {
    auto* p = CreateMaybeMessage<::crdc::airi::Header>(GetArena());
    header_ = p;
  }
  return header_;
}
inline ::crdc::airi::Header* Image2::mutable_header() {
  // @@protoc_insertion_point(field_mutable:crdc.airi.Image2.header)
  return _internal_mutable_header();
}
inline void Image2::set_allocated_header(::crdc::airi::Header* header) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(header_);
  }
  if (header) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(header)->GetArena();
    if (message_arena != submessage_arena) {
      header = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, header, submessage_arena);
    }
    _has_bits_[0] |= 0x00000004u;
  } else {
    _has_bits_[0] &= ~0x00000004u;
  }
  header_ = header;
  // @@protoc_insertion_point(field_set_allocated:crdc.airi.Image2.header)
}

// optional uint32 height = 2;
inline bool Image2::_internal_has_height() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool Image2::has_height() const {
  return _internal_has_height();
}
inline void Image2::clear_height() {
  height_ = 0u;
  _has_bits_[0] &= ~0x00000008u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Image2::_internal_height() const {
  return height_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Image2::height() const {
  // @@protoc_insertion_point(field_get:crdc.airi.Image2.height)
  return _internal_height();
}
inline void Image2::_internal_set_height(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _has_bits_[0] |= 0x00000008u;
  height_ = value;
}
inline void Image2::set_height(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_height(value);
  // @@protoc_insertion_point(field_set:crdc.airi.Image2.height)
}

// optional uint32 width = 3;
inline bool Image2::_internal_has_width() const {
  bool value = (_has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline bool Image2::has_width() const {
  return _internal_has_width();
}
inline void Image2::clear_width() {
  width_ = 0u;
  _has_bits_[0] &= ~0x00000010u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Image2::_internal_width() const {
  return width_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Image2::width() const {
  // @@protoc_insertion_point(field_get:crdc.airi.Image2.width)
  return _internal_width();
}
inline void Image2::_internal_set_width(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _has_bits_[0] |= 0x00000010u;
  width_ = value;
}
inline void Image2::set_width(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_width(value);
  // @@protoc_insertion_point(field_set:crdc.airi.Image2.width)
}

// optional .crdc.airi.Image2.Compression compression = 4;
inline bool Image2::_internal_has_compression() const {
  bool value = (_has_bits_[0] & 0x00000080u) != 0;
  return value;
}
inline bool Image2::has_compression() const {
  return _internal_has_compression();
}
inline void Image2::clear_compression() {
  compression_ = 1;
  _has_bits_[0] &= ~0x00000080u;
}
inline ::crdc::airi::Image2_Compression Image2::_internal_compression() const {
  return static_cast< ::crdc::airi::Image2_Compression >(compression_);
}
inline ::crdc::airi::Image2_Compression Image2::compression() const {
  // @@protoc_insertion_point(field_get:crdc.airi.Image2.compression)
  return _internal_compression();
}
inline void Image2::_internal_set_compression(::crdc::airi::Image2_Compression value) {
  assert(::crdc::airi::Image2_Compression_IsValid(value));
  _has_bits_[0] |= 0x00000080u;
  compression_ = value;
}
inline void Image2::set_compression(::crdc::airi::Image2_Compression value) {
  _internal_set_compression(value);
  // @@protoc_insertion_point(field_set:crdc.airi.Image2.compression)
}

// optional uint32 step = 5;
inline bool Image2::_internal_has_step() const {
  bool value = (_has_bits_[0] & 0x00000020u) != 0;
  return value;
}
inline bool Image2::has_step() const {
  return _internal_has_step();
}
inline void Image2::clear_step() {
  step_ = 0u;
  _has_bits_[0] &= ~0x00000020u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Image2::_internal_step() const {
  return step_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Image2::step() const {
  // @@protoc_insertion_point(field_get:crdc.airi.Image2.step)
  return _internal_step();
}
inline void Image2::_internal_set_step(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _has_bits_[0] |= 0x00000020u;
  step_ = value;
}
inline void Image2::set_step(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_step(value);
  // @@protoc_insertion_point(field_set:crdc.airi.Image2.step)
}

// optional bytes data = 6;
inline bool Image2::_internal_has_data() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool Image2::has_data() const {
  return _internal_has_data();
}
inline void Image2::clear_data() {
  data_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& Image2::data() const {
  // @@protoc_insertion_point(field_get:crdc.airi.Image2.data)
  return _internal_data();
}
inline void Image2::set_data(const std::string& value) {
  _internal_set_data(value);
  // @@protoc_insertion_point(field_set:crdc.airi.Image2.data)
}
inline std::string* Image2::mutable_data() {
  // @@protoc_insertion_point(field_mutable:crdc.airi.Image2.data)
  return _internal_mutable_data();
}
inline const std::string& Image2::_internal_data() const {
  return data_.Get();
}
inline void Image2::_internal_set_data(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  data_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void Image2::set_data(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  data_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:crdc.airi.Image2.data)
}
inline void Image2::set_data(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  data_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:crdc.airi.Image2.data)
}
inline void Image2::set_data(const void* value,
    size_t size) {
  _has_bits_[0] |= 0x00000001u;
  data_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:crdc.airi.Image2.data)
}
inline std::string* Image2::_internal_mutable_data() {
  _has_bits_[0] |= 0x00000001u;
  return data_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* Image2::release_data() {
  // @@protoc_insertion_point(field_release:crdc.airi.Image2.data)
  if (!_internal_has_data()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return data_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void Image2::set_allocated_data(std::string* data) {
  if (data != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  data_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), data,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:crdc.airi.Image2.data)
}

// optional string type = 7;
inline bool Image2::_internal_has_type() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool Image2::has_type() const {
  return _internal_has_type();
}
inline void Image2::clear_type() {
  type_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000002u;
}
inline const std::string& Image2::type() const {
  // @@protoc_insertion_point(field_get:crdc.airi.Image2.type)
  return _internal_type();
}
inline void Image2::set_type(const std::string& value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:crdc.airi.Image2.type)
}
inline std::string* Image2::mutable_type() {
  // @@protoc_insertion_point(field_mutable:crdc.airi.Image2.type)
  return _internal_mutable_type();
}
inline const std::string& Image2::_internal_type() const {
  return type_.Get();
}
inline void Image2::_internal_set_type(const std::string& value) {
  _has_bits_[0] |= 0x00000002u;
  type_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void Image2::set_type(std::string&& value) {
  _has_bits_[0] |= 0x00000002u;
  type_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:crdc.airi.Image2.type)
}
inline void Image2::set_type(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000002u;
  type_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:crdc.airi.Image2.type)
}
inline void Image2::set_type(const char* value,
    size_t size) {
  _has_bits_[0] |= 0x00000002u;
  type_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:crdc.airi.Image2.type)
}
inline std::string* Image2::_internal_mutable_type() {
  _has_bits_[0] |= 0x00000002u;
  return type_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* Image2::release_type() {
  // @@protoc_insertion_point(field_release:crdc.airi.Image2.type)
  if (!_internal_has_type()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000002u;
  return type_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void Image2::set_allocated_type(std::string* type) {
  if (type != nullptr) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  type_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), type,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:crdc.airi.Image2.type)
}

// optional uint32 exposuretime = 8;
inline bool Image2::_internal_has_exposuretime() const {
  bool value = (_has_bits_[0] & 0x00000040u) != 0;
  return value;
}
inline bool Image2::has_exposuretime() const {
  return _internal_has_exposuretime();
}
inline void Image2::clear_exposuretime() {
  exposuretime_ = 0u;
  _has_bits_[0] &= ~0x00000040u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Image2::_internal_exposuretime() const {
  return exposuretime_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Image2::exposuretime() const {
  // @@protoc_insertion_point(field_get:crdc.airi.Image2.exposuretime)
  return _internal_exposuretime();
}
inline void Image2::_internal_set_exposuretime(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _has_bits_[0] |= 0x00000040u;
  exposuretime_ = value;
}
inline void Image2::set_exposuretime(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_exposuretime(value);
  // @@protoc_insertion_point(field_set:crdc.airi.Image2.exposuretime)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace airi
}  // namespace crdc

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::crdc::airi::Image2_Compression> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::crdc::airi::Image2_Compression>() {
  return ::crdc::airi::Image2_Compression_descriptor();
}
template <> struct is_proto_enum< ::crdc::airi::PixelFormat> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::crdc::airi::PixelFormat>() {
  return ::crdc::airi::PixelFormat_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_image_2eproto
