// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ins.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_ins_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_ins_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3014000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3014000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "header.pb.h"
#include "geometry.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_ins_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_ins_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_ins_2eproto;
namespace crdc {
namespace airi {
class Ins;
class InsDefaultTypeInternal;
extern InsDefaultTypeInternal _Ins_default_instance_;
class InsStat;
class InsStatDefaultTypeInternal;
extern InsStatDefaultTypeInternal _InsStat_default_instance_;
}  // namespace airi
}  // namespace crdc
PROTOBUF_NAMESPACE_OPEN
template<> ::crdc::airi::Ins* Arena::CreateMaybeMessage<::crdc::airi::Ins>(Arena*);
template<> ::crdc::airi::InsStat* Arena::CreateMaybeMessage<::crdc::airi::InsStat>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace crdc {
namespace airi {

enum Ins_Type : int {
  Ins_Type_INVALID = 0,
  Ins_Type_CONVERGING = 1,
  Ins_Type_GOOD = 2
};
bool Ins_Type_IsValid(int value);
constexpr Ins_Type Ins_Type_Type_MIN = Ins_Type_INVALID;
constexpr Ins_Type Ins_Type_Type_MAX = Ins_Type_GOOD;
constexpr int Ins_Type_Type_ARRAYSIZE = Ins_Type_Type_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Ins_Type_descriptor();
template<typename T>
inline const std::string& Ins_Type_Name(T enum_t_value) {
  static_assert(::std::is_same<T, Ins_Type>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function Ins_Type_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    Ins_Type_descriptor(), enum_t_value);
}
inline bool Ins_Type_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, Ins_Type* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<Ins_Type>(
    Ins_Type_descriptor(), name, value);
}
// ===================================================================

class InsStat PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:crdc.airi.InsStat) */ {
 public:
  inline InsStat() : InsStat(nullptr) {}
  virtual ~InsStat();

  InsStat(const InsStat& from);
  InsStat(InsStat&& from) noexcept
    : InsStat() {
    *this = ::std::move(from);
  }

  inline InsStat& operator=(const InsStat& from) {
    CopyFrom(from);
    return *this;
  }
  inline InsStat& operator=(InsStat&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const InsStat& default_instance();

  static inline const InsStat* internal_default_instance() {
    return reinterpret_cast<const InsStat*>(
               &_InsStat_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(InsStat& a, InsStat& b) {
    a.Swap(&b);
  }
  inline void Swap(InsStat* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(InsStat* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline InsStat* New() const final {
    return CreateMaybeMessage<InsStat>(nullptr);
  }

  InsStat* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<InsStat>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const InsStat& from);
  void MergeFrom(const InsStat& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(InsStat* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "crdc.airi.InsStat";
  }
  protected:
  explicit InsStat(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_ins_2eproto);
    return ::descriptor_table_ins_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kHeaderFieldNumber = 1,
    kInsStatusFieldNumber = 2,
    kPosTypeFieldNumber = 3,
  };
  // optional .crdc.airi.Header header = 1;
  bool has_header() const;
  private:
  bool _internal_has_header() const;
  public:
  void clear_header();
  const ::crdc::airi::Header& header() const;
  ::crdc::airi::Header* release_header();
  ::crdc::airi::Header* mutable_header();
  void set_allocated_header(::crdc::airi::Header* header);
  private:
  const ::crdc::airi::Header& _internal_header() const;
  ::crdc::airi::Header* _internal_mutable_header();
  public:
  void unsafe_arena_set_allocated_header(
      ::crdc::airi::Header* header);
  ::crdc::airi::Header* unsafe_arena_release_header();

  // optional uint32 ins_status = 2;
  bool has_ins_status() const;
  private:
  bool _internal_has_ins_status() const;
  public:
  void clear_ins_status();
  ::PROTOBUF_NAMESPACE_ID::uint32 ins_status() const;
  void set_ins_status(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_ins_status() const;
  void _internal_set_ins_status(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // optional uint32 pos_type = 3;
  bool has_pos_type() const;
  private:
  bool _internal_has_pos_type() const;
  public:
  void clear_pos_type();
  ::PROTOBUF_NAMESPACE_ID::uint32 pos_type() const;
  void set_pos_type(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_pos_type() const;
  void _internal_set_pos_type(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:crdc.airi.InsStat)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::crdc::airi::Header* header_;
  ::PROTOBUF_NAMESPACE_ID::uint32 ins_status_;
  ::PROTOBUF_NAMESPACE_ID::uint32 pos_type_;
  friend struct ::TableStruct_ins_2eproto;
};
// -------------------------------------------------------------------

class Ins PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:crdc.airi.Ins) */ {
 public:
  inline Ins() : Ins(nullptr) {}
  virtual ~Ins();

  Ins(const Ins& from);
  Ins(Ins&& from) noexcept
    : Ins() {
    *this = ::std::move(from);
  }

  inline Ins& operator=(const Ins& from) {
    CopyFrom(from);
    return *this;
  }
  inline Ins& operator=(Ins&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Ins& default_instance();

  static inline const Ins* internal_default_instance() {
    return reinterpret_cast<const Ins*>(
               &_Ins_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Ins& a, Ins& b) {
    a.Swap(&b);
  }
  inline void Swap(Ins* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Ins* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Ins* New() const final {
    return CreateMaybeMessage<Ins>(nullptr);
  }

  Ins* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Ins>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Ins& from);
  void MergeFrom(const Ins& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Ins* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "crdc.airi.Ins";
  }
  protected:
  explicit Ins(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_ins_2eproto);
    return ::descriptor_table_ins_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  typedef Ins_Type Type;
  static constexpr Type INVALID =
    Ins_Type_INVALID;
  static constexpr Type CONVERGING =
    Ins_Type_CONVERGING;
  static constexpr Type GOOD =
    Ins_Type_GOOD;
  static inline bool Type_IsValid(int value) {
    return Ins_Type_IsValid(value);
  }
  static constexpr Type Type_MIN =
    Ins_Type_Type_MIN;
  static constexpr Type Type_MAX =
    Ins_Type_Type_MAX;
  static constexpr int Type_ARRAYSIZE =
    Ins_Type_Type_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  Type_descriptor() {
    return Ins_Type_descriptor();
  }
  template<typename T>
  static inline const std::string& Type_Name(T enum_t_value) {
    static_assert(::std::is_same<T, Type>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function Type_Name.");
    return Ins_Type_Name(enum_t_value);
  }
  static inline bool Type_Parse(::PROTOBUF_NAMESPACE_ID::ConstStringParam name,
      Type* value) {
    return Ins_Type_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kPositionCovarianceFieldNumber = 9,
    kEulerAnglesCovarianceFieldNumber = 10,
    kLinearVelocityCovarianceFieldNumber = 11,
    kAngularVelocityCovarianceFieldNumber = 12,
    kLinearAccelerationCovarianceFieldNumber = 13,
    kHeaderFieldNumber = 1,
    kPositionFieldNumber = 4,
    kEulerAnglesFieldNumber = 5,
    kLinearVelocityFieldNumber = 6,
    kAngularVelocityFieldNumber = 7,
    kLinearAccelerationFieldNumber = 8,
    kMeasurementTimeFieldNumber = 2,
    kTypeFieldNumber = 3,
  };
  // repeated float position_covariance = 9 [packed = true];
  int position_covariance_size() const;
  private:
  int _internal_position_covariance_size() const;
  public:
  void clear_position_covariance();
  private:
  float _internal_position_covariance(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      _internal_position_covariance() const;
  void _internal_add_position_covariance(float value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      _internal_mutable_position_covariance();
  public:
  float position_covariance(int index) const;
  void set_position_covariance(int index, float value);
  void add_position_covariance(float value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      position_covariance() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      mutable_position_covariance();

  // repeated float euler_angles_covariance = 10 [packed = true];
  int euler_angles_covariance_size() const;
  private:
  int _internal_euler_angles_covariance_size() const;
  public:
  void clear_euler_angles_covariance();
  private:
  float _internal_euler_angles_covariance(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      _internal_euler_angles_covariance() const;
  void _internal_add_euler_angles_covariance(float value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      _internal_mutable_euler_angles_covariance();
  public:
  float euler_angles_covariance(int index) const;
  void set_euler_angles_covariance(int index, float value);
  void add_euler_angles_covariance(float value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      euler_angles_covariance() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      mutable_euler_angles_covariance();

  // repeated float linear_velocity_covariance = 11 [packed = true];
  int linear_velocity_covariance_size() const;
  private:
  int _internal_linear_velocity_covariance_size() const;
  public:
  void clear_linear_velocity_covariance();
  private:
  float _internal_linear_velocity_covariance(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      _internal_linear_velocity_covariance() const;
  void _internal_add_linear_velocity_covariance(float value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      _internal_mutable_linear_velocity_covariance();
  public:
  float linear_velocity_covariance(int index) const;
  void set_linear_velocity_covariance(int index, float value);
  void add_linear_velocity_covariance(float value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      linear_velocity_covariance() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      mutable_linear_velocity_covariance();

  // repeated float angular_velocity_covariance = 12 [packed = true];
  int angular_velocity_covariance_size() const;
  private:
  int _internal_angular_velocity_covariance_size() const;
  public:
  void clear_angular_velocity_covariance();
  private:
  float _internal_angular_velocity_covariance(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      _internal_angular_velocity_covariance() const;
  void _internal_add_angular_velocity_covariance(float value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      _internal_mutable_angular_velocity_covariance();
  public:
  float angular_velocity_covariance(int index) const;
  void set_angular_velocity_covariance(int index, float value);
  void add_angular_velocity_covariance(float value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      angular_velocity_covariance() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      mutable_angular_velocity_covariance();

  // repeated float linear_acceleration_covariance = 13 [packed = true];
  int linear_acceleration_covariance_size() const;
  private:
  int _internal_linear_acceleration_covariance_size() const;
  public:
  void clear_linear_acceleration_covariance();
  private:
  float _internal_linear_acceleration_covariance(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      _internal_linear_acceleration_covariance() const;
  void _internal_add_linear_acceleration_covariance(float value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      _internal_mutable_linear_acceleration_covariance();
  public:
  float linear_acceleration_covariance(int index) const;
  void set_linear_acceleration_covariance(int index, float value);
  void add_linear_acceleration_covariance(float value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      linear_acceleration_covariance() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      mutable_linear_acceleration_covariance();

  // optional .crdc.airi.Header header = 1;
  bool has_header() const;
  private:
  bool _internal_has_header() const;
  public:
  void clear_header();
  const ::crdc::airi::Header& header() const;
  ::crdc::airi::Header* release_header();
  ::crdc::airi::Header* mutable_header();
  void set_allocated_header(::crdc::airi::Header* header);
  private:
  const ::crdc::airi::Header& _internal_header() const;
  ::crdc::airi::Header* _internal_mutable_header();
  public:
  void unsafe_arena_set_allocated_header(
      ::crdc::airi::Header* header);
  ::crdc::airi::Header* unsafe_arena_release_header();

  // optional .crdc.airi.PointLLH position = 4;
  bool has_position() const;
  private:
  bool _internal_has_position() const;
  public:
  void clear_position();
  const ::crdc::airi::PointLLH& position() const;
  ::crdc::airi::PointLLH* release_position();
  ::crdc::airi::PointLLH* mutable_position();
  void set_allocated_position(::crdc::airi::PointLLH* position);
  private:
  const ::crdc::airi::PointLLH& _internal_position() const;
  ::crdc::airi::PointLLH* _internal_mutable_position();
  public:
  void unsafe_arena_set_allocated_position(
      ::crdc::airi::PointLLH* position);
  ::crdc::airi::PointLLH* unsafe_arena_release_position();

  // optional .crdc.airi.Point3D euler_angles = 5;
  bool has_euler_angles() const;
  private:
  bool _internal_has_euler_angles() const;
  public:
  void clear_euler_angles();
  const ::crdc::airi::Point3D& euler_angles() const;
  ::crdc::airi::Point3D* release_euler_angles();
  ::crdc::airi::Point3D* mutable_euler_angles();
  void set_allocated_euler_angles(::crdc::airi::Point3D* euler_angles);
  private:
  const ::crdc::airi::Point3D& _internal_euler_angles() const;
  ::crdc::airi::Point3D* _internal_mutable_euler_angles();
  public:
  void unsafe_arena_set_allocated_euler_angles(
      ::crdc::airi::Point3D* euler_angles);
  ::crdc::airi::Point3D* unsafe_arena_release_euler_angles();

  // optional .crdc.airi.Point3D linear_velocity = 6;
  bool has_linear_velocity() const;
  private:
  bool _internal_has_linear_velocity() const;
  public:
  void clear_linear_velocity();
  const ::crdc::airi::Point3D& linear_velocity() const;
  ::crdc::airi::Point3D* release_linear_velocity();
  ::crdc::airi::Point3D* mutable_linear_velocity();
  void set_allocated_linear_velocity(::crdc::airi::Point3D* linear_velocity);
  private:
  const ::crdc::airi::Point3D& _internal_linear_velocity() const;
  ::crdc::airi::Point3D* _internal_mutable_linear_velocity();
  public:
  void unsafe_arena_set_allocated_linear_velocity(
      ::crdc::airi::Point3D* linear_velocity);
  ::crdc::airi::Point3D* unsafe_arena_release_linear_velocity();

  // optional .crdc.airi.Point3D angular_velocity = 7;
  bool has_angular_velocity() const;
  private:
  bool _internal_has_angular_velocity() const;
  public:
  void clear_angular_velocity();
  const ::crdc::airi::Point3D& angular_velocity() const;
  ::crdc::airi::Point3D* release_angular_velocity();
  ::crdc::airi::Point3D* mutable_angular_velocity();
  void set_allocated_angular_velocity(::crdc::airi::Point3D* angular_velocity);
  private:
  const ::crdc::airi::Point3D& _internal_angular_velocity() const;
  ::crdc::airi::Point3D* _internal_mutable_angular_velocity();
  public:
  void unsafe_arena_set_allocated_angular_velocity(
      ::crdc::airi::Point3D* angular_velocity);
  ::crdc::airi::Point3D* unsafe_arena_release_angular_velocity();

  // optional .crdc.airi.Point3D linear_acceleration = 8;
  bool has_linear_acceleration() const;
  private:
  bool _internal_has_linear_acceleration() const;
  public:
  void clear_linear_acceleration();
  const ::crdc::airi::Point3D& linear_acceleration() const;
  ::crdc::airi::Point3D* release_linear_acceleration();
  ::crdc::airi::Point3D* mutable_linear_acceleration();
  void set_allocated_linear_acceleration(::crdc::airi::Point3D* linear_acceleration);
  private:
  const ::crdc::airi::Point3D& _internal_linear_acceleration() const;
  ::crdc::airi::Point3D* _internal_mutable_linear_acceleration();
  public:
  void unsafe_arena_set_allocated_linear_acceleration(
      ::crdc::airi::Point3D* linear_acceleration);
  ::crdc::airi::Point3D* unsafe_arena_release_linear_acceleration();

  // optional double measurement_time = 2;
  bool has_measurement_time() const;
  private:
  bool _internal_has_measurement_time() const;
  public:
  void clear_measurement_time();
  double measurement_time() const;
  void set_measurement_time(double value);
  private:
  double _internal_measurement_time() const;
  void _internal_set_measurement_time(double value);
  public:

  // optional .crdc.airi.Ins.Type type = 3;
  bool has_type() const;
  private:
  bool _internal_has_type() const;
  public:
  void clear_type();
  ::crdc::airi::Ins_Type type() const;
  void set_type(::crdc::airi::Ins_Type value);
  private:
  ::crdc::airi::Ins_Type _internal_type() const;
  void _internal_set_type(::crdc::airi::Ins_Type value);
  public:

  // @@protoc_insertion_point(class_scope:crdc.airi.Ins)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float > position_covariance_;
  mutable std::atomic<int> _position_covariance_cached_byte_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float > euler_angles_covariance_;
  mutable std::atomic<int> _euler_angles_covariance_cached_byte_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float > linear_velocity_covariance_;
  mutable std::atomic<int> _linear_velocity_covariance_cached_byte_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float > angular_velocity_covariance_;
  mutable std::atomic<int> _angular_velocity_covariance_cached_byte_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float > linear_acceleration_covariance_;
  mutable std::atomic<int> _linear_acceleration_covariance_cached_byte_size_;
  ::crdc::airi::Header* header_;
  ::crdc::airi::PointLLH* position_;
  ::crdc::airi::Point3D* euler_angles_;
  ::crdc::airi::Point3D* linear_velocity_;
  ::crdc::airi::Point3D* angular_velocity_;
  ::crdc::airi::Point3D* linear_acceleration_;
  double measurement_time_;
  int type_;
  friend struct ::TableStruct_ins_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// InsStat

// optional .crdc.airi.Header header = 1;
inline bool InsStat::_internal_has_header() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || header_ != nullptr);
  return value;
}
inline bool InsStat::has_header() const {
  return _internal_has_header();
}
inline const ::crdc::airi::Header& InsStat::_internal_header() const {
  const ::crdc::airi::Header* p = header_;
  return p != nullptr ? *p : reinterpret_cast<const ::crdc::airi::Header&>(
      ::crdc::airi::_Header_default_instance_);
}
inline const ::crdc::airi::Header& InsStat::header() const {
  // @@protoc_insertion_point(field_get:crdc.airi.InsStat.header)
  return _internal_header();
}
inline void InsStat::unsafe_arena_set_allocated_header(
    ::crdc::airi::Header* header) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(header_);
  }
  header_ = header;
  if (header) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:crdc.airi.InsStat.header)
}
inline ::crdc::airi::Header* InsStat::release_header() {
  _has_bits_[0] &= ~0x00000001u;
  ::crdc::airi::Header* temp = header_;
  header_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::crdc::airi::Header* InsStat::unsafe_arena_release_header() {
  // @@protoc_insertion_point(field_release:crdc.airi.InsStat.header)
  _has_bits_[0] &= ~0x00000001u;
  ::crdc::airi::Header* temp = header_;
  header_ = nullptr;
  return temp;
}
inline ::crdc::airi::Header* InsStat::_internal_mutable_header() {
  _has_bits_[0] |= 0x00000001u;
  if (header_ == nullptr) {
    auto* p = CreateMaybeMessage<::crdc::airi::Header>(GetArena());
    header_ = p;
  }
  return header_;
}
inline ::crdc::airi::Header* InsStat::mutable_header() {
  // @@protoc_insertion_point(field_mutable:crdc.airi.InsStat.header)
  return _internal_mutable_header();
}
inline void InsStat::set_allocated_header(::crdc::airi::Header* header) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(header_);
  }
  if (header) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(header)->GetArena();
    if (message_arena != submessage_arena) {
      header = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, header, submessage_arena);
    }
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  header_ = header;
  // @@protoc_insertion_point(field_set_allocated:crdc.airi.InsStat.header)
}

// optional uint32 ins_status = 2;
inline bool InsStat::_internal_has_ins_status() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool InsStat::has_ins_status() const {
  return _internal_has_ins_status();
}
inline void InsStat::clear_ins_status() {
  ins_status_ = 0u;
  _has_bits_[0] &= ~0x00000002u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 InsStat::_internal_ins_status() const {
  return ins_status_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 InsStat::ins_status() const {
  // @@protoc_insertion_point(field_get:crdc.airi.InsStat.ins_status)
  return _internal_ins_status();
}
inline void InsStat::_internal_set_ins_status(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _has_bits_[0] |= 0x00000002u;
  ins_status_ = value;
}
inline void InsStat::set_ins_status(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_ins_status(value);
  // @@protoc_insertion_point(field_set:crdc.airi.InsStat.ins_status)
}

// optional uint32 pos_type = 3;
inline bool InsStat::_internal_has_pos_type() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool InsStat::has_pos_type() const {
  return _internal_has_pos_type();
}
inline void InsStat::clear_pos_type() {
  pos_type_ = 0u;
  _has_bits_[0] &= ~0x00000004u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 InsStat::_internal_pos_type() const {
  return pos_type_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 InsStat::pos_type() const {
  // @@protoc_insertion_point(field_get:crdc.airi.InsStat.pos_type)
  return _internal_pos_type();
}
inline void InsStat::_internal_set_pos_type(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _has_bits_[0] |= 0x00000004u;
  pos_type_ = value;
}
inline void InsStat::set_pos_type(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_pos_type(value);
  // @@protoc_insertion_point(field_set:crdc.airi.InsStat.pos_type)
}

// -------------------------------------------------------------------

// Ins

// optional .crdc.airi.Header header = 1;
inline bool Ins::_internal_has_header() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || header_ != nullptr);
  return value;
}
inline bool Ins::has_header() const {
  return _internal_has_header();
}
inline const ::crdc::airi::Header& Ins::_internal_header() const {
  const ::crdc::airi::Header* p = header_;
  return p != nullptr ? *p : reinterpret_cast<const ::crdc::airi::Header&>(
      ::crdc::airi::_Header_default_instance_);
}
inline const ::crdc::airi::Header& Ins::header() const {
  // @@protoc_insertion_point(field_get:crdc.airi.Ins.header)
  return _internal_header();
}
inline void Ins::unsafe_arena_set_allocated_header(
    ::crdc::airi::Header* header) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(header_);
  }
  header_ = header;
  if (header) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:crdc.airi.Ins.header)
}
inline ::crdc::airi::Header* Ins::release_header() {
  _has_bits_[0] &= ~0x00000001u;
  ::crdc::airi::Header* temp = header_;
  header_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::crdc::airi::Header* Ins::unsafe_arena_release_header() {
  // @@protoc_insertion_point(field_release:crdc.airi.Ins.header)
  _has_bits_[0] &= ~0x00000001u;
  ::crdc::airi::Header* temp = header_;
  header_ = nullptr;
  return temp;
}
inline ::crdc::airi::Header* Ins::_internal_mutable_header() {
  _has_bits_[0] |= 0x00000001u;
  if (header_ == nullptr) {
    auto* p = CreateMaybeMessage<::crdc::airi::Header>(GetArena());
    header_ = p;
  }
  return header_;
}
inline ::crdc::airi::Header* Ins::mutable_header() {
  // @@protoc_insertion_point(field_mutable:crdc.airi.Ins.header)
  return _internal_mutable_header();
}
inline void Ins::set_allocated_header(::crdc::airi::Header* header) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(header_);
  }
  if (header) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(header)->GetArena();
    if (message_arena != submessage_arena) {
      header = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, header, submessage_arena);
    }
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  header_ = header;
  // @@protoc_insertion_point(field_set_allocated:crdc.airi.Ins.header)
}

// optional double measurement_time = 2;
inline bool Ins::_internal_has_measurement_time() const {
  bool value = (_has_bits_[0] & 0x00000040u) != 0;
  return value;
}
inline bool Ins::has_measurement_time() const {
  return _internal_has_measurement_time();
}
inline void Ins::clear_measurement_time() {
  measurement_time_ = 0;
  _has_bits_[0] &= ~0x00000040u;
}
inline double Ins::_internal_measurement_time() const {
  return measurement_time_;
}
inline double Ins::measurement_time() const {
  // @@protoc_insertion_point(field_get:crdc.airi.Ins.measurement_time)
  return _internal_measurement_time();
}
inline void Ins::_internal_set_measurement_time(double value) {
  _has_bits_[0] |= 0x00000040u;
  measurement_time_ = value;
}
inline void Ins::set_measurement_time(double value) {
  _internal_set_measurement_time(value);
  // @@protoc_insertion_point(field_set:crdc.airi.Ins.measurement_time)
}

// optional .crdc.airi.Ins.Type type = 3;
inline bool Ins::_internal_has_type() const {
  bool value = (_has_bits_[0] & 0x00000080u) != 0;
  return value;
}
inline bool Ins::has_type() const {
  return _internal_has_type();
}
inline void Ins::clear_type() {
  type_ = 0;
  _has_bits_[0] &= ~0x00000080u;
}
inline ::crdc::airi::Ins_Type Ins::_internal_type() const {
  return static_cast< ::crdc::airi::Ins_Type >(type_);
}
inline ::crdc::airi::Ins_Type Ins::type() const {
  // @@protoc_insertion_point(field_get:crdc.airi.Ins.type)
  return _internal_type();
}
inline void Ins::_internal_set_type(::crdc::airi::Ins_Type value) {
  assert(::crdc::airi::Ins_Type_IsValid(value));
  _has_bits_[0] |= 0x00000080u;
  type_ = value;
}
inline void Ins::set_type(::crdc::airi::Ins_Type value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:crdc.airi.Ins.type)
}

// optional .crdc.airi.PointLLH position = 4;
inline bool Ins::_internal_has_position() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || position_ != nullptr);
  return value;
}
inline bool Ins::has_position() const {
  return _internal_has_position();
}
inline const ::crdc::airi::PointLLH& Ins::_internal_position() const {
  const ::crdc::airi::PointLLH* p = position_;
  return p != nullptr ? *p : reinterpret_cast<const ::crdc::airi::PointLLH&>(
      ::crdc::airi::_PointLLH_default_instance_);
}
inline const ::crdc::airi::PointLLH& Ins::position() const {
  // @@protoc_insertion_point(field_get:crdc.airi.Ins.position)
  return _internal_position();
}
inline void Ins::unsafe_arena_set_allocated_position(
    ::crdc::airi::PointLLH* position) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(position_);
  }
  position_ = position;
  if (position) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:crdc.airi.Ins.position)
}
inline ::crdc::airi::PointLLH* Ins::release_position() {
  _has_bits_[0] &= ~0x00000002u;
  ::crdc::airi::PointLLH* temp = position_;
  position_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::crdc::airi::PointLLH* Ins::unsafe_arena_release_position() {
  // @@protoc_insertion_point(field_release:crdc.airi.Ins.position)
  _has_bits_[0] &= ~0x00000002u;
  ::crdc::airi::PointLLH* temp = position_;
  position_ = nullptr;
  return temp;
}
inline ::crdc::airi::PointLLH* Ins::_internal_mutable_position() {
  _has_bits_[0] |= 0x00000002u;
  if (position_ == nullptr) {
    auto* p = CreateMaybeMessage<::crdc::airi::PointLLH>(GetArena());
    position_ = p;
  }
  return position_;
}
inline ::crdc::airi::PointLLH* Ins::mutable_position() {
  // @@protoc_insertion_point(field_mutable:crdc.airi.Ins.position)
  return _internal_mutable_position();
}
inline void Ins::set_allocated_position(::crdc::airi::PointLLH* position) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(position_);
  }
  if (position) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(position)->GetArena();
    if (message_arena != submessage_arena) {
      position = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, position, submessage_arena);
    }
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  position_ = position;
  // @@protoc_insertion_point(field_set_allocated:crdc.airi.Ins.position)
}

// optional .crdc.airi.Point3D euler_angles = 5;
inline bool Ins::_internal_has_euler_angles() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  PROTOBUF_ASSUME(!value || euler_angles_ != nullptr);
  return value;
}
inline bool Ins::has_euler_angles() const {
  return _internal_has_euler_angles();
}
inline const ::crdc::airi::Point3D& Ins::_internal_euler_angles() const {
  const ::crdc::airi::Point3D* p = euler_angles_;
  return p != nullptr ? *p : reinterpret_cast<const ::crdc::airi::Point3D&>(
      ::crdc::airi::_Point3D_default_instance_);
}
inline const ::crdc::airi::Point3D& Ins::euler_angles() const {
  // @@protoc_insertion_point(field_get:crdc.airi.Ins.euler_angles)
  return _internal_euler_angles();
}
inline void Ins::unsafe_arena_set_allocated_euler_angles(
    ::crdc::airi::Point3D* euler_angles) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(euler_angles_);
  }
  euler_angles_ = euler_angles;
  if (euler_angles) {
    _has_bits_[0] |= 0x00000004u;
  } else {
    _has_bits_[0] &= ~0x00000004u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:crdc.airi.Ins.euler_angles)
}
inline ::crdc::airi::Point3D* Ins::release_euler_angles() {
  _has_bits_[0] &= ~0x00000004u;
  ::crdc::airi::Point3D* temp = euler_angles_;
  euler_angles_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::crdc::airi::Point3D* Ins::unsafe_arena_release_euler_angles() {
  // @@protoc_insertion_point(field_release:crdc.airi.Ins.euler_angles)
  _has_bits_[0] &= ~0x00000004u;
  ::crdc::airi::Point3D* temp = euler_angles_;
  euler_angles_ = nullptr;
  return temp;
}
inline ::crdc::airi::Point3D* Ins::_internal_mutable_euler_angles() {
  _has_bits_[0] |= 0x00000004u;
  if (euler_angles_ == nullptr) {
    auto* p = CreateMaybeMessage<::crdc::airi::Point3D>(GetArena());
    euler_angles_ = p;
  }
  return euler_angles_;
}
inline ::crdc::airi::Point3D* Ins::mutable_euler_angles() {
  // @@protoc_insertion_point(field_mutable:crdc.airi.Ins.euler_angles)
  return _internal_mutable_euler_angles();
}
inline void Ins::set_allocated_euler_angles(::crdc::airi::Point3D* euler_angles) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(euler_angles_);
  }
  if (euler_angles) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(euler_angles)->GetArena();
    if (message_arena != submessage_arena) {
      euler_angles = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, euler_angles, submessage_arena);
    }
    _has_bits_[0] |= 0x00000004u;
  } else {
    _has_bits_[0] &= ~0x00000004u;
  }
  euler_angles_ = euler_angles;
  // @@protoc_insertion_point(field_set_allocated:crdc.airi.Ins.euler_angles)
}

// optional .crdc.airi.Point3D linear_velocity = 6;
inline bool Ins::_internal_has_linear_velocity() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  PROTOBUF_ASSUME(!value || linear_velocity_ != nullptr);
  return value;
}
inline bool Ins::has_linear_velocity() const {
  return _internal_has_linear_velocity();
}
inline const ::crdc::airi::Point3D& Ins::_internal_linear_velocity() const {
  const ::crdc::airi::Point3D* p = linear_velocity_;
  return p != nullptr ? *p : reinterpret_cast<const ::crdc::airi::Point3D&>(
      ::crdc::airi::_Point3D_default_instance_);
}
inline const ::crdc::airi::Point3D& Ins::linear_velocity() const {
  // @@protoc_insertion_point(field_get:crdc.airi.Ins.linear_velocity)
  return _internal_linear_velocity();
}
inline void Ins::unsafe_arena_set_allocated_linear_velocity(
    ::crdc::airi::Point3D* linear_velocity) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(linear_velocity_);
  }
  linear_velocity_ = linear_velocity;
  if (linear_velocity) {
    _has_bits_[0] |= 0x00000008u;
  } else {
    _has_bits_[0] &= ~0x00000008u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:crdc.airi.Ins.linear_velocity)
}
inline ::crdc::airi::Point3D* Ins::release_linear_velocity() {
  _has_bits_[0] &= ~0x00000008u;
  ::crdc::airi::Point3D* temp = linear_velocity_;
  linear_velocity_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::crdc::airi::Point3D* Ins::unsafe_arena_release_linear_velocity() {
  // @@protoc_insertion_point(field_release:crdc.airi.Ins.linear_velocity)
  _has_bits_[0] &= ~0x00000008u;
  ::crdc::airi::Point3D* temp = linear_velocity_;
  linear_velocity_ = nullptr;
  return temp;
}
inline ::crdc::airi::Point3D* Ins::_internal_mutable_linear_velocity() {
  _has_bits_[0] |= 0x00000008u;
  if (linear_velocity_ == nullptr) {
    auto* p = CreateMaybeMessage<::crdc::airi::Point3D>(GetArena());
    linear_velocity_ = p;
  }
  return linear_velocity_;
}
inline ::crdc::airi::Point3D* Ins::mutable_linear_velocity() {
  // @@protoc_insertion_point(field_mutable:crdc.airi.Ins.linear_velocity)
  return _internal_mutable_linear_velocity();
}
inline void Ins::set_allocated_linear_velocity(::crdc::airi::Point3D* linear_velocity) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(linear_velocity_);
  }
  if (linear_velocity) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(linear_velocity)->GetArena();
    if (message_arena != submessage_arena) {
      linear_velocity = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, linear_velocity, submessage_arena);
    }
    _has_bits_[0] |= 0x00000008u;
  } else {
    _has_bits_[0] &= ~0x00000008u;
  }
  linear_velocity_ = linear_velocity;
  // @@protoc_insertion_point(field_set_allocated:crdc.airi.Ins.linear_velocity)
}

// optional .crdc.airi.Point3D angular_velocity = 7;
inline bool Ins::_internal_has_angular_velocity() const {
  bool value = (_has_bits_[0] & 0x00000010u) != 0;
  PROTOBUF_ASSUME(!value || angular_velocity_ != nullptr);
  return value;
}
inline bool Ins::has_angular_velocity() const {
  return _internal_has_angular_velocity();
}
inline const ::crdc::airi::Point3D& Ins::_internal_angular_velocity() const {
  const ::crdc::airi::Point3D* p = angular_velocity_;
  return p != nullptr ? *p : reinterpret_cast<const ::crdc::airi::Point3D&>(
      ::crdc::airi::_Point3D_default_instance_);
}
inline const ::crdc::airi::Point3D& Ins::angular_velocity() const {
  // @@protoc_insertion_point(field_get:crdc.airi.Ins.angular_velocity)
  return _internal_angular_velocity();
}
inline void Ins::unsafe_arena_set_allocated_angular_velocity(
    ::crdc::airi::Point3D* angular_velocity) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(angular_velocity_);
  }
  angular_velocity_ = angular_velocity;
  if (angular_velocity) {
    _has_bits_[0] |= 0x00000010u;
  } else {
    _has_bits_[0] &= ~0x00000010u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:crdc.airi.Ins.angular_velocity)
}
inline ::crdc::airi::Point3D* Ins::release_angular_velocity() {
  _has_bits_[0] &= ~0x00000010u;
  ::crdc::airi::Point3D* temp = angular_velocity_;
  angular_velocity_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::crdc::airi::Point3D* Ins::unsafe_arena_release_angular_velocity() {
  // @@protoc_insertion_point(field_release:crdc.airi.Ins.angular_velocity)
  _has_bits_[0] &= ~0x00000010u;
  ::crdc::airi::Point3D* temp = angular_velocity_;
  angular_velocity_ = nullptr;
  return temp;
}
inline ::crdc::airi::Point3D* Ins::_internal_mutable_angular_velocity() {
  _has_bits_[0] |= 0x00000010u;
  if (angular_velocity_ == nullptr) {
    auto* p = CreateMaybeMessage<::crdc::airi::Point3D>(GetArena());
    angular_velocity_ = p;
  }
  return angular_velocity_;
}
inline ::crdc::airi::Point3D* Ins::mutable_angular_velocity() {
  // @@protoc_insertion_point(field_mutable:crdc.airi.Ins.angular_velocity)
  return _internal_mutable_angular_velocity();
}
inline void Ins::set_allocated_angular_velocity(::crdc::airi::Point3D* angular_velocity) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(angular_velocity_);
  }
  if (angular_velocity) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(angular_velocity)->GetArena();
    if (message_arena != submessage_arena) {
      angular_velocity = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, angular_velocity, submessage_arena);
    }
    _has_bits_[0] |= 0x00000010u;
  } else {
    _has_bits_[0] &= ~0x00000010u;
  }
  angular_velocity_ = angular_velocity;
  // @@protoc_insertion_point(field_set_allocated:crdc.airi.Ins.angular_velocity)
}

// optional .crdc.airi.Point3D linear_acceleration = 8;
inline bool Ins::_internal_has_linear_acceleration() const {
  bool value = (_has_bits_[0] & 0x00000020u) != 0;
  PROTOBUF_ASSUME(!value || linear_acceleration_ != nullptr);
  return value;
}
inline bool Ins::has_linear_acceleration() const {
  return _internal_has_linear_acceleration();
}
inline const ::crdc::airi::Point3D& Ins::_internal_linear_acceleration() const {
  const ::crdc::airi::Point3D* p = linear_acceleration_;
  return p != nullptr ? *p : reinterpret_cast<const ::crdc::airi::Point3D&>(
      ::crdc::airi::_Point3D_default_instance_);
}
inline const ::crdc::airi::Point3D& Ins::linear_acceleration() const {
  // @@protoc_insertion_point(field_get:crdc.airi.Ins.linear_acceleration)
  return _internal_linear_acceleration();
}
inline void Ins::unsafe_arena_set_allocated_linear_acceleration(
    ::crdc::airi::Point3D* linear_acceleration) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(linear_acceleration_);
  }
  linear_acceleration_ = linear_acceleration;
  if (linear_acceleration) {
    _has_bits_[0] |= 0x00000020u;
  } else {
    _has_bits_[0] &= ~0x00000020u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:crdc.airi.Ins.linear_acceleration)
}
inline ::crdc::airi::Point3D* Ins::release_linear_acceleration() {
  _has_bits_[0] &= ~0x00000020u;
  ::crdc::airi::Point3D* temp = linear_acceleration_;
  linear_acceleration_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::crdc::airi::Point3D* Ins::unsafe_arena_release_linear_acceleration() {
  // @@protoc_insertion_point(field_release:crdc.airi.Ins.linear_acceleration)
  _has_bits_[0] &= ~0x00000020u;
  ::crdc::airi::Point3D* temp = linear_acceleration_;
  linear_acceleration_ = nullptr;
  return temp;
}
inline ::crdc::airi::Point3D* Ins::_internal_mutable_linear_acceleration() {
  _has_bits_[0] |= 0x00000020u;
  if (linear_acceleration_ == nullptr) {
    auto* p = CreateMaybeMessage<::crdc::airi::Point3D>(GetArena());
    linear_acceleration_ = p;
  }
  return linear_acceleration_;
}
inline ::crdc::airi::Point3D* Ins::mutable_linear_acceleration() {
  // @@protoc_insertion_point(field_mutable:crdc.airi.Ins.linear_acceleration)
  return _internal_mutable_linear_acceleration();
}
inline void Ins::set_allocated_linear_acceleration(::crdc::airi::Point3D* linear_acceleration) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(linear_acceleration_);
  }
  if (linear_acceleration) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(linear_acceleration)->GetArena();
    if (message_arena != submessage_arena) {
      linear_acceleration = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, linear_acceleration, submessage_arena);
    }
    _has_bits_[0] |= 0x00000020u;
  } else {
    _has_bits_[0] &= ~0x00000020u;
  }
  linear_acceleration_ = linear_acceleration;
  // @@protoc_insertion_point(field_set_allocated:crdc.airi.Ins.linear_acceleration)
}

// repeated float position_covariance = 9 [packed = true];
inline int Ins::_internal_position_covariance_size() const {
  return position_covariance_.size();
}
inline int Ins::position_covariance_size() const {
  return _internal_position_covariance_size();
}
inline void Ins::clear_position_covariance() {
  position_covariance_.Clear();
}
inline float Ins::_internal_position_covariance(int index) const {
  return position_covariance_.Get(index);
}
inline float Ins::position_covariance(int index) const {
  // @@protoc_insertion_point(field_get:crdc.airi.Ins.position_covariance)
  return _internal_position_covariance(index);
}
inline void Ins::set_position_covariance(int index, float value) {
  position_covariance_.Set(index, value);
  // @@protoc_insertion_point(field_set:crdc.airi.Ins.position_covariance)
}
inline void Ins::_internal_add_position_covariance(float value) {
  position_covariance_.Add(value);
}
inline void Ins::add_position_covariance(float value) {
  _internal_add_position_covariance(value);
  // @@protoc_insertion_point(field_add:crdc.airi.Ins.position_covariance)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
Ins::_internal_position_covariance() const {
  return position_covariance_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
Ins::position_covariance() const {
  // @@protoc_insertion_point(field_list:crdc.airi.Ins.position_covariance)
  return _internal_position_covariance();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
Ins::_internal_mutable_position_covariance() {
  return &position_covariance_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
Ins::mutable_position_covariance() {
  // @@protoc_insertion_point(field_mutable_list:crdc.airi.Ins.position_covariance)
  return _internal_mutable_position_covariance();
}

// repeated float euler_angles_covariance = 10 [packed = true];
inline int Ins::_internal_euler_angles_covariance_size() const {
  return euler_angles_covariance_.size();
}
inline int Ins::euler_angles_covariance_size() const {
  return _internal_euler_angles_covariance_size();
}
inline void Ins::clear_euler_angles_covariance() {
  euler_angles_covariance_.Clear();
}
inline float Ins::_internal_euler_angles_covariance(int index) const {
  return euler_angles_covariance_.Get(index);
}
inline float Ins::euler_angles_covariance(int index) const {
  // @@protoc_insertion_point(field_get:crdc.airi.Ins.euler_angles_covariance)
  return _internal_euler_angles_covariance(index);
}
inline void Ins::set_euler_angles_covariance(int index, float value) {
  euler_angles_covariance_.Set(index, value);
  // @@protoc_insertion_point(field_set:crdc.airi.Ins.euler_angles_covariance)
}
inline void Ins::_internal_add_euler_angles_covariance(float value) {
  euler_angles_covariance_.Add(value);
}
inline void Ins::add_euler_angles_covariance(float value) {
  _internal_add_euler_angles_covariance(value);
  // @@protoc_insertion_point(field_add:crdc.airi.Ins.euler_angles_covariance)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
Ins::_internal_euler_angles_covariance() const {
  return euler_angles_covariance_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
Ins::euler_angles_covariance() const {
  // @@protoc_insertion_point(field_list:crdc.airi.Ins.euler_angles_covariance)
  return _internal_euler_angles_covariance();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
Ins::_internal_mutable_euler_angles_covariance() {
  return &euler_angles_covariance_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
Ins::mutable_euler_angles_covariance() {
  // @@protoc_insertion_point(field_mutable_list:crdc.airi.Ins.euler_angles_covariance)
  return _internal_mutable_euler_angles_covariance();
}

// repeated float linear_velocity_covariance = 11 [packed = true];
inline int Ins::_internal_linear_velocity_covariance_size() const {
  return linear_velocity_covariance_.size();
}
inline int Ins::linear_velocity_covariance_size() const {
  return _internal_linear_velocity_covariance_size();
}
inline void Ins::clear_linear_velocity_covariance() {
  linear_velocity_covariance_.Clear();
}
inline float Ins::_internal_linear_velocity_covariance(int index) const {
  return linear_velocity_covariance_.Get(index);
}
inline float Ins::linear_velocity_covariance(int index) const {
  // @@protoc_insertion_point(field_get:crdc.airi.Ins.linear_velocity_covariance)
  return _internal_linear_velocity_covariance(index);
}
inline void Ins::set_linear_velocity_covariance(int index, float value) {
  linear_velocity_covariance_.Set(index, value);
  // @@protoc_insertion_point(field_set:crdc.airi.Ins.linear_velocity_covariance)
}
inline void Ins::_internal_add_linear_velocity_covariance(float value) {
  linear_velocity_covariance_.Add(value);
}
inline void Ins::add_linear_velocity_covariance(float value) {
  _internal_add_linear_velocity_covariance(value);
  // @@protoc_insertion_point(field_add:crdc.airi.Ins.linear_velocity_covariance)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
Ins::_internal_linear_velocity_covariance() const {
  return linear_velocity_covariance_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
Ins::linear_velocity_covariance() const {
  // @@protoc_insertion_point(field_list:crdc.airi.Ins.linear_velocity_covariance)
  return _internal_linear_velocity_covariance();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
Ins::_internal_mutable_linear_velocity_covariance() {
  return &linear_velocity_covariance_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
Ins::mutable_linear_velocity_covariance() {
  // @@protoc_insertion_point(field_mutable_list:crdc.airi.Ins.linear_velocity_covariance)
  return _internal_mutable_linear_velocity_covariance();
}

// repeated float angular_velocity_covariance = 12 [packed = true];
inline int Ins::_internal_angular_velocity_covariance_size() const {
  return angular_velocity_covariance_.size();
}
inline int Ins::angular_velocity_covariance_size() const {
  return _internal_angular_velocity_covariance_size();
}
inline void Ins::clear_angular_velocity_covariance() {
  angular_velocity_covariance_.Clear();
}
inline float Ins::_internal_angular_velocity_covariance(int index) const {
  return angular_velocity_covariance_.Get(index);
}
inline float Ins::angular_velocity_covariance(int index) const {
  // @@protoc_insertion_point(field_get:crdc.airi.Ins.angular_velocity_covariance)
  return _internal_angular_velocity_covariance(index);
}
inline void Ins::set_angular_velocity_covariance(int index, float value) {
  angular_velocity_covariance_.Set(index, value);
  // @@protoc_insertion_point(field_set:crdc.airi.Ins.angular_velocity_covariance)
}
inline void Ins::_internal_add_angular_velocity_covariance(float value) {
  angular_velocity_covariance_.Add(value);
}
inline void Ins::add_angular_velocity_covariance(float value) {
  _internal_add_angular_velocity_covariance(value);
  // @@protoc_insertion_point(field_add:crdc.airi.Ins.angular_velocity_covariance)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
Ins::_internal_angular_velocity_covariance() const {
  return angular_velocity_covariance_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
Ins::angular_velocity_covariance() const {
  // @@protoc_insertion_point(field_list:crdc.airi.Ins.angular_velocity_covariance)
  return _internal_angular_velocity_covariance();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
Ins::_internal_mutable_angular_velocity_covariance() {
  return &angular_velocity_covariance_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
Ins::mutable_angular_velocity_covariance() {
  // @@protoc_insertion_point(field_mutable_list:crdc.airi.Ins.angular_velocity_covariance)
  return _internal_mutable_angular_velocity_covariance();
}

// repeated float linear_acceleration_covariance = 13 [packed = true];
inline int Ins::_internal_linear_acceleration_covariance_size() const {
  return linear_acceleration_covariance_.size();
}
inline int Ins::linear_acceleration_covariance_size() const {
  return _internal_linear_acceleration_covariance_size();
}
inline void Ins::clear_linear_acceleration_covariance() {
  linear_acceleration_covariance_.Clear();
}
inline float Ins::_internal_linear_acceleration_covariance(int index) const {
  return linear_acceleration_covariance_.Get(index);
}
inline float Ins::linear_acceleration_covariance(int index) const {
  // @@protoc_insertion_point(field_get:crdc.airi.Ins.linear_acceleration_covariance)
  return _internal_linear_acceleration_covariance(index);
}
inline void Ins::set_linear_acceleration_covariance(int index, float value) {
  linear_acceleration_covariance_.Set(index, value);
  // @@protoc_insertion_point(field_set:crdc.airi.Ins.linear_acceleration_covariance)
}
inline void Ins::_internal_add_linear_acceleration_covariance(float value) {
  linear_acceleration_covariance_.Add(value);
}
inline void Ins::add_linear_acceleration_covariance(float value) {
  _internal_add_linear_acceleration_covariance(value);
  // @@protoc_insertion_point(field_add:crdc.airi.Ins.linear_acceleration_covariance)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
Ins::_internal_linear_acceleration_covariance() const {
  return linear_acceleration_covariance_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
Ins::linear_acceleration_covariance() const {
  // @@protoc_insertion_point(field_list:crdc.airi.Ins.linear_acceleration_covariance)
  return _internal_linear_acceleration_covariance();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
Ins::_internal_mutable_linear_acceleration_covariance() {
  return &linear_acceleration_covariance_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
Ins::mutable_linear_acceleration_covariance() {
  // @@protoc_insertion_point(field_mutable_list:crdc.airi.Ins.linear_acceleration_covariance)
  return _internal_mutable_linear_acceleration_covariance();
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace airi
}  // namespace crdc

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::crdc::airi::Ins_Type> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::crdc::airi::Ins_Type>() {
  return ::crdc::airi::Ins_Type_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_ins_2eproto
